development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://nmstdeplnhjiql:e48cf2eed524bb4e086cfc37f83e324c16b4460c6df81c6c505e11165f1dec3d@ec2-23-21-235-142.compute-1.amazonaws.com:5432/df6gm6fluu4tb9
